# Schema for the configuration files of the google_analytics_counter module.

google_analytics_counter.settings:
  type: config_object
  label: 'Settings'
  mapping:
    general_settings:
      type: mapping
      label: 'General Settings'
      mapping:
        client_id:
          type: string
          label: 'Client ID created for the app.'
        client_secret:
          type: string
          label: 'Client Secret created for the app.'
        redirect_uri:
          type: string
          label: 'Used to override the host for the callback uri.'
        cron_interval:
          type: integer
          label: 'Minimum time between Google Analytics data fetching.'
        chunk_to_fetch:
          type: integer
          label: 'Number of items to fetch from Google Analytics in one request.'
        cache_length:
          type: integer
          label: 'The minimum time in hours to elapse between getting fresh data for the same query from Google Analytics.'
        queue_time:
          type: integer
          label: 'The length of time the queue should be run.'
        end_date:
          type: string
          label: 'The end date for Google Analytics queries.'
        start_date:
          type: string
          label: 'The start date for Google Analytics queries.'
        custom_start_date:
          type: string
          label: 'The fixed start date for Google Analytics queries.'
        custom_end_date:
          type: string
          label: 'The fixed end date for Google Analytics queries.'
        custom_start_day:
          type: string
          label: 'The start day for Google Analytics queries.'
        custom_end_day:
          type: string
          label: 'The rnd day for Google Analytics queries.'
        project_name:
          type: string
          label: 'The machine name of the Google project.'
        profile_id:
          type: string
          label: 'The Google Analytics view to use.'
        gac_type_page:
          type: string
          label: 'The page node type.'
        ga4_property_id:
          type: string
          label: 'Google Analytics 4 Property ID'
        credentials_json_path:
          type: string
          label: 'Path to the service account credentials.json'
        node_last_x_days:
          type: integer
          label: 'Update pageviews for content created in the last X days'
        node_not_newer_than_x_days:
          type: integer
          label: 'Update pageviews for content not newer than X days'
        node_last_x_nid:
          type: integer
          label: 'Update pageviews for last X content'
        metric:
          type: string
          label: 'Metric'
        dimension:
          type: string
          label: 'Dimension'
        result_processor:
          type: string
          label: 'Result processor'