_core:
  default_config_hash: ByOVf1cU9r5NkZ4ieBJ7k9sUid6jb03ojMN1gjJ0-OU
site_key: 6LfbWh4TAAAAAHmEstaTD4vze4P5buXm823mq9Rg
secret_key: 6LfbWh4TAAAAAEZgkxQR1Xswvt-kmKDgwmFx8A3P
verify_hostname: false
use_globally: true
widget:
  theme: light
  type: image
  size: ''
  noscript: true
